routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//  Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

 Route::redirect("/","users");
 Route::resource("/users", UsersController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(20);
        return view("layouts/index", compact("users"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("layouts/form");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request)
    {
        User::create($request->only("name","email"));
        return redirect()->route("users.index")->withSuccess("Created user" ." ". $request->name);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view("layouts/show" , compact("user"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view("layouts/form", compact("user"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {
        $user->update($request->only(["name","email"]));
        return redirect()->route("users.index")->withSuccess("Updated user" ." ". $user->name);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route("users.index")->withDanger("Deleted user" ." ". $user->name);
    }
}

resources/views/layouts/form.blade.php
@extends("layouts/layout")

@section("title", isset($user) ? "Update"." ".$user->name : "Create user")

@section("content")
    <a class="btn btn-secondary mb-3" href="{{route('users.index')}}" role="button">Back</a>
    <form method="POST"
        @if(isset($user))
            action="{{route('users.update', $user)}}" 
        @else
            action="{{route('users.store')}}"
        @endif   
        >
            @csrf

        @isset($user)
            @method("PUT")
        @endisset      
        <div class="col">
            <div class="col-5">
                <input value="{{ old('name', isset($user) ? $user->name :null)}}" name="name" type="text" class="form-control" placeholder="name" aria-label="name">
                @error("name")
                    <div class="alert alert-danger">{{$message}}</div> 
                @enderror
            </div>
           
            <div class="col-5">
                <input value="{{ old('email', isset($user) ? $user->email :null)}}" name="email" type="text" class="form-control mt-2" placeholder="email" aria-label="email">
                @error("email")
                    <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-3">{{isset($user) ? "Change user" :"Add user"}}</button>
    </form>    
@endsection

resources/views/layouts/index.blade.php
@extends("layouts/layout")

@section("navbar")
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar scroll</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Link
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
            </li>
        </ul>
        <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        </div>
    </div>
    </nav>

@endsection

@section("title","Users")

@section("content")

<a href="{{route('users.create')}}" class="btn btn-primary btn-md " role="button"><i class=" p-1 fas fa-user-plus"></i>Create user</a>
    <table class="table">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
            @foreach($users as $user)
                <tr>
                <th scope="row">{{ $user->id }}</th>
                <td > <a href="{{route('users.show' , $user)}}"> {{ $user->name }} </a> </td>
                <td> <a href="{{route('users.show' , $user)}}"> {{ $user->email }} </a> </td>
                <td>
                    <form method="POST" action="{{route('users.destroy', $user)}}">
                        <a class="btn btn-warning col-4" href="{{route('users.edit', $user)}}" role="button"><i class="fas fa-pencil-alt p-1"></i>Edit</a>
                        @csrf
                        @method("DELETE")
                        <button type="submit" class="btn btn-danger col-4" role="button"><i class="far fa-trash-alt p-1"></i>Delete</button>
                    </form>
                </td>
                </tr>
            @endforeach
        
    </tbody>
    </table>
    {{$users->links()}}
@endsection

resources/views/layouts/show.blade.php
@extends("layouts/layout")

@section("title","User" . " " . $user->name)

@section("content")
<a class="btn btn-secondary mb-3" href="{{route('users.index')}}" role="button">Back</a>
<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
        <li class="list-group-item"> Id: {{$user->id}} </li>
        <li class="list-group-item"> Name: {{$user->name}} </li>
        <li class="list-group-item"> Email: {{$user->email}} </li>
        <li class="list-group-item"> Created: {{$user->created_at->format("d/m/y G:i:s")}} </li>
        <li class="list-group-item"> Updated: {{$user->updated_at->format("d/m/y G:i:s")}} </li>
  </ul>
    <form method="POST" class=" list-group" action="{{route('users.destroy', $user)}}">
        <a class="btn btn-warning list-group-item rounded-0" href="{{route('users.edit', $user)}}" role="button"><i class="fas fa-pencil-alt p-1"></i>Edit</a>
        @csrf
        @method("DELETE")
        <button type="submit" class="btn btn-danger list-group-item rounded-0" role="button"><i class="far fa-trash-alt p-1"></i>Delete</button>
    </form>
</div>
@endsection